# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
                     # To run you must have writing permissions on the repository
                     # But note, this file needs to be monitored in the main branch

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: actions/setup-dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: dotnet restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: Pack
      run: dotnet pack --no-build --output ${{ github.workspace }}/artifacts --configuration Release
    - name: Publish
      if: github.event_name == 'workflow_dispatch'
      run: dotnet nuget push ${{ github.workspace }}/artifacts/*.nupkg --source "nuget.org" --api-key "${{ secrets.NUGET_API_KEY }}"
